baseURL = 'https://simoneeti.github.io/docs/'
languageCode = 'es'
title = 'Simón Vintrob'
theme = 'risotto'
publishDir = 'docs'

[params]
noindex = false
# Sidebar: about/bio
[params.about]
title = "Simón"
description = "Ser humano"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/simoneeti"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:vintrob.simon@gmail.com"


[languages]
  [languages.en]
    languageName = "English"
    title = "Simón Vintrob"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Seguir leyendo..."
    readOtherPosts = "Otras entradas"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Simón Vintrob"
      logoHomeLink = "/docs/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "musica"
        name = "Música rara que voy descubriendo"
        url = "https://www.youtube.com/watch?v=EuqvLiB7i7g&list=PL-Gj1Cs9_OLykPiEBOLYAIeszf1XHZoUj&index=25"
